spring:
  application:
    name: flight-Function-api
  datasource:
    url: jdbc:mysql://localhost:3306/flight_db
    username: root
    password: ww123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  # 让 Spring Boot 自动执行 SQL 初始化脚本
  sql:
    init:
      # mode: always
      mode: never
      schema-locations:
        - classpath:scripts/schema.sql
      data-locations:
        - classpath:scripts/data.sql
secret:
  key: ww's secret key123456789012345678901234567890
server:
  port: 8081

