spring:
  application:
    name: flight-Function-api
  datasource:
    url: jdbc:mysql://localhost:3306/flight_db
    username: root
    password: ww123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://wangwei-flightdb.cj6gcogsidzt.ap-southeast-2.rds.amazonaws.com:3306/flight_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    # username: admin
    # password: ww123456
    # driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  # 让 Spring Boot 自动执行 SQL 初始化脚本
  sql:
    init:
      # mode: never or always
      mode: never
      schema-locations:
        - classpath:scripts/schema.sql
      data-locations:
        - classpath:scripts/data.sql
jwt:
  secret: s a secret keyThis ietThis is a secret keyThis ietThis is a secret keyThis is a secThis is a secret keyThis is a secret keyThis is a secret keyThis is a secret keyThis is a secret keyret keyThis is a secret keyThis is a secretis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyTis is a secret keyT keyThis is a secret key key
server:
  port: 8081


# spring.application.name=cicd-aws
# spring.datasource.url=${SPRING_DATABASE_URL}
# spring.datasource.username=${SPRING_DATABASE_USERNAME}
# spring.datasource.password=${SPRING_DATABASE_PASSWORD}
# spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
# spring.sql.init.mode=${SPRING_SQL_INIT_MODE}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
