spring:
  application:
    name: flight-Function-api
  datasource:
    url: jdbc:mysql://localhost:3306/ndis_db
    username: root
    password: ww123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081
