version: '3.8'
services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ww123456
  #     MYSQL_DATABASE: flight_db
  #   ports:
  #     - "3307:3307"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
   
  flight-api:
    build: .
    container_name: flight-api
    # depends_on:
    #   - mysql
    ports:
      - "8080:8080"
    # environment:
    #   SPRING_DATABASE_URL: jdbc:mysql://mysql:3306/flight_db
    #   SPRING_DATABASE_USERNAME: root
    #   SPRING_DATABASE_PASSWORD: ww123456
    #   SPRING_JPA_HIBERNATE_DDL_AUTO: update
    #   SPRING_SQL_INIT_MODE: always
 
volumes:
  mysql_data:
 
#  docker - compose up --build 

# # 先构建镜像
# docker-compose build  
# # 再启动容器
# docker-compose up 