spring:
  application:
    name: test-api
  datasource:
    url: jdbc:mysql://localhost:3306/flight_db
    username: root
    password: ww123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082


# spring.application.name=cicd-aws
# spring.datasource.url=${SPRING_DATABASE_URL}
# spring.datasource.username=${SPRING_DATABASE_USERNAME}
# spring.datasource.password=${SPRING_DATABASE_PASSWORD}
# spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
# spring.sql.init.mode=${SPRING_SQL_INIT_MODE}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
